server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: farmchainx-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/farmchainx?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Adi@2006}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
      expiration: 86400000 # 24 hours

logging:
  level:
    com.farmchainx: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG